---
apiVersion: v1
kind: Namespace
metadata:
  name: examboom
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: examboom
  name: exb-front-deploy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: exb-front
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: exb-front
    spec:
      containers:
      - image: public.ecr.aws/f0w1w3j5/examboom-front:latest
        imagePullPolicy: Always
        name: exb-front
        ports:
        - containerPort: 80  
        resources:
          limits:
            cpu: 120m
          requests:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  namespace: examboom
  name: exb-front-service
    
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: exb-front
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: examboom
  name: exb-front-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    external-dns.alpha.kubernetes.io/hostname: eks.viassh.com
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: exb-back-service
                port: 
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: exb-front-service
                port: 
                  number: 80

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: exb-front-hpa
  namespace: examboom
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: exb-front-deploy
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
  # metrics:
  # - type: Resource
  #   resource:
  #     name: cpu
  #     target:
  #       type: Utilization
  #       averageUtilization: 20              