apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: examboom
  name: exb-back-deploy
  
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: exb-back
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: exb-back
    spec:
      containers:
      - image: public.ecr.aws/f0w1w3j5/examboom-back:v1.2
        imagePullPolicy: Always
        name: exb-back
        ports:
        - containerPort: 8080  
        resources:
          limits:
            cpu: 300m
            memory: 700Mi
          requests:
            cpu: 300m
            memory: 600Mi
---
apiVersion: v1
kind: Service
metadata:
  namespace: examboom
  name: exb-back-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: exb-back

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: exb-back-hpa
  namespace: examboom
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: exb-back-deploy
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60

  # metrics:
  # - type: Resource
  #   resource:
  #     name: cpu
  #     target:
  #       type: Utilization
  #       averageUtilization: 20