apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: examboom
  name: exb-front-deploy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: exb-front
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: exb-front
    spec:
      containers:
      - image: public.ecr.aws/f0w1w3j5/examboom-back:latest
        imagePullPolicy: Always
        name: exb-front
        ports:
        - containerPort: 80