---
apiVersion: v1
kind: Namespace
metadata:
  name: examboom
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: examboom
  name: exb-front-deploy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: exb-front
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: exb-front
    spec:
      containers:
      - image: public.ecr.aws/f0w1w3j5/examboom-front:latest
        imagePullPolicy: Always
        name: exb-front
        ports:
        - containerPort: 80  
---
apiVersion: v1
kind: Service
metadata:
  namespace: examboom
  name: exb-front-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: exb-front
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: examboom
  name: exb-front-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /api/*
            backend:
              serviceName: exb-back-service
              servicePort: 8080
    
          - path: /*
            backend:
              serviceName: exb-front-service
              servicePort: 8080